apiVersion: v1
kind: Service
metadata:
  name: fiap-pos-tech-api-service
  namespace: fiap-pos-tech
  labels:
    app: fiap-pos-tech-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: fiap-pos-tech-api