apiVersion: v1
kind: Service
metadata:
  name: fiap-pos-tech-db-service
  namespace: fiap-pos-tech
  labels:
    app: fiap-pos-tech-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: fiap-pos-tech-db